version: '3'
services:
  db:
    image: mariadb:latest
    restart: "no"
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: "no"
    environment:
      PMA_HOST: db
      PMA_USER: username
      PMA_PASSWORD: password
    ports:
      - "8080:80"
