name: Draft a Release and Upload Asset

on:
  push:
    branches:
      - master
#    paths:
#      - VERSION

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B assembly:assembly -DdescriptorId=jar-with-dependencies --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Get the version
        id: get_version
        run: echo "::set-output name=VERSION::$(cat VERSION)"

      - name: Create a release draft
        id: release-draft
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body_path: Release.txt
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          files: |
            ./remote_orchestration/install.sh
            ./remote_orchestration/protein-search-mgmt.service
            ./remote_orchestration/protein-search-web.service
            ./JOIntegration/target/JOIntegration-1.0-SNAPSHOT-jar-with-dependencies.jar
            ./JOIntegration/src/main/resources/run.properties.example
            

